import Foundation

/// Persisted record of a paired iOS device. Stored on the Mac in Keychain.
public struct PairRecord: Codable, Equatable, Identifiable, Hashable, Sendable {
    public let id: String              // device id (UUID generated by iOS)
    public let deviceName: String
    public let bearerToken: String
    public var apnsToken: String?
    public let pairedAt: Date
    public var lastSeenAt: Date

    public init(id: String, deviceName: String, bearerToken: String, apnsToken: String?, pairedAt: Date = Date(), lastSeenAt: Date = Date()) {
        self.id = id
        self.deviceName = deviceName
        self.bearerToken = bearerToken
        self.apnsToken = apnsToken
        self.pairedAt = pairedAt
        self.lastSeenAt = lastSeenAt
    }
}

public enum PairCodec {
    public static let encoder: JSONEncoder = {
        let e = JSONEncoder()
        e.dateEncodingStrategy = .iso8601
        return e
    }()

    public static let decoder: JSONDecoder = {
        let d = JSONDecoder()
        d.dateDecodingStrategy = .iso8601
        return d
    }()

    public static func encodeMessage(_ message: WireMessage) throws -> Data {
        try encoder.encode(message)
    }

    public static func decodeMessage(_ data: Data) throws -> WireMessage {
        try decoder.decode(WireMessage.self, from: data)
    }

    public static func encodeInvite(_ invite: PairingInvite) throws -> String {
        try encoder.encode(invite).base64EncodedString()
    }

    public static func decodeInvite(_ encoded: String) throws -> PairingInvite {
        guard let data = Data(base64Encoded: encoded) else {
            throw NSError(domain: "PairingProtocol", code: 1, userInfo: [NSLocalizedDescriptionKey: "Invalid pairing code"])
        }
        return try decoder.decode(PairingInvite.self, from: data)
    }
}
